{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WELCOME TO GUESS ME!\n",
      "Let me select a number between 1 and 100\n",
      "If your guess is more than 10 away from my number, I'll tell you you're COLD\n",
      "If your guess is within 10 of my number, I'll tell you you're WARM\n",
      "If your guess is farther than your most recent guess, I'll say you're getting COLDER\n",
      "If your guess is closer than your most recent guess, I'll say you're getting WARMER\n",
      "LET'S PLAY!\n",
      "Make your guess\n",
      "50\n",
      "COLDER!\n",
      "Make your guess\n",
      "25\n",
      "WARM!\n",
      "Make your guess\n",
      "24\n",
      "WARM!\n",
      "Make your guess\n",
      "1\n",
      "COLD!\n",
      "Make your guess\n",
      "100\n",
      "COLD!\n",
      "Make your guess\n",
      "6\n",
      "COLD!\n",
      "Make your guess\n",
      "2\n",
      "COLD!\n",
      "Make your guess\n",
      "12\n",
      "WARM!\n",
      "Make your guess\n",
      "35\n",
      "COLD!\n",
      "Make your guess\n",
      "25\n",
      "Do you want to know the answer?\n",
      "Press 1 for Yes and 0 to continue\n",
      "1\n",
      "17\n",
      "Try next time, Cheers!\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "num = random.randint(1,100)                      # To select any random integer between 1 & 100\n",
    "\n",
    "print(\"WELCOME TO GUESS ME!\")\n",
    "print(\"Let me select a number between 1 and 100\")\n",
    "print(\"If your guess is more than 10 away from my number, I'll tell you you're COLD\")\n",
    "print(\"If your guess is within 10 of my number, I'll tell you you're WARM\")\n",
    "print(\"If your guess is farther than your most recent guess, I'll say you're getting COLDER\")\n",
    "print(\"If your guess is closer than your most recent guess, I'll say you're getting WARMER\")\n",
    "print(\"LET'S PLAY!\")\n",
    "guesses=[0]\n",
    "while(True):\n",
    "    guess = int(input('Make your guess\\n'))\n",
    "    if guess<1 or guess>100:                                             # to ensure guess lies within the range\n",
    "        print(\"OUT OF BOUNDS!\")\n",
    "        continue\n",
    "    \n",
    "    if guess==num:\n",
    "        print('CONGRATULATIONS!, you guessed the correct answer in {} attempts.\\n'.format(len(guesses)))\n",
    "        break\n",
    "    guesses.append(guess)                                            # all the incorrect guesses are added to  list\n",
    "    if len(guesses)>10:                                              # after nine trials player may choose to know the answer\n",
    "        temp = int(input('Do you want to know the answer?\\nPress 1 for Yes and 0 to continue\\n'))\n",
    "        if temp == 1:\n",
    "            print(num)\n",
    "            print('Try next time, Cheers!')\n",
    "            break\n",
    "    if guesses[-2]==0:                                                 # when testing the first guess, guesses[-2]==0, which evaluates to False\n",
    "                                                                        # and brings us down to the second section\n",
    "        if abs(num-guess) < abs(num-guesses[-2]):\n",
    "            print('WARMER!')\n",
    "        else:\n",
    "            print('COLDER!')\n",
    "    else:\n",
    "        if abs(num-guess) <= 10:\n",
    "            print('WARM!')\n",
    "        else:\n",
    "            print('COLD!')    \n",
    "   \n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WELCOME TO GUESS ME!\n",
      "Let me select a number between 1 and 100\n",
      "If your guess is more than 10 away from my number, I'll tell you you're COLD\n",
      "If your guess is within 10 of my number, I'll tell you you're WARM\n",
      "If your guess is farther than your most recent guess, I'll say you're getting COLDER\n",
      "If your guess is closer than your most recent guess, I'll say you're getting WARMER\n",
      "LET'S PLAY!\n",
      "Make your guess\n",
      "50\n",
      "COLDER!\n",
      "Make your guess\n",
      "23\n",
      "COLD!\n",
      "Make your guess\n",
      "25\n",
      "COLD!\n",
      "Make your guess\n",
      "69\n",
      "COLD!\n",
      "Make your guess\n",
      "98\n",
      "COLD!\n",
      "Make your guess\n",
      "11\n",
      "WARM!\n",
      "Make your guess\n",
      "25\n",
      "COLD!\n",
      "Make your guess\n",
      "36\n",
      "COLD!\n",
      "Make your guess\n",
      "25\n",
      "COLD!\n",
      "Make your guess\n",
      "68\n",
      "Do you want to know the answer?\n",
      "Press 1 for Yes and 0 to continue\n",
      "0\n",
      "COLD!\n",
      "Make your guess\n",
      "25\n",
      "Do you want to know the answer?\n",
      "Press 1 for Yes and 0 to continue\n",
      "5155455118\n",
      "COLD!\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "num = random.randint(1,100)                      # To select any random integer between 1 & 100\n",
    "\n",
    "print(\"WELCOME TO GUESS ME!\")\n",
    "print(\"Let me select a number between 1 and 100\")\n",
    "print(\"If your guess is more than 10 away from my number, I'll tell you you're COLD\")\n",
    "print(\"If your guess is within 10 of my number, I'll tell you you're WARM\")\n",
    "print(\"If your guess is farther than your most recent guess, I'll say you're getting COLDER\")\n",
    "print(\"If your guess is closer than your most recent guess, I'll say you're getting WARMER\")\n",
    "print(\"LET'S PLAY!\")\n",
    "guesses=[0]\n",
    "while(True):\n",
    "    guess = int(input('Make your guess\\n'))\n",
    "    if guess<1 or guess>100:                                             # to ensure guess lies within the range\n",
    "        print(\"OUT OF BOUNDS!\")\n",
    "        continue\n",
    "    \n",
    "    if guess==num:\n",
    "        print('CONGRATULATIONS!, you guessed the correct answer in {} attempts.\\n'.format(len(guesses)))\n",
    "        break\n",
    "    guesses.append(guess)                                            # all the incorrect guesses are added to  list\n",
    "    if len(guesses)>10:                                              # after nine trials player may choose to know the answer\n",
    "        temp = int(input('Do you want to know the answer?\\nPress 1 for Yes and 0 to continue\\n'))\n",
    "        if temp == 1:\n",
    "            print(num)\n",
    "            print('Try next time, Cheers!')\n",
    "            break\n",
    "    if guesses[-2]==0:                                                 # when testing the first guess, guesses[-2]==0, which evaluates to False\n",
    "                                                                        # and brings us down to the second section\n",
    "        if abs(num-guess) < abs(num-guesses[-2]):\n",
    "            print('WARMER!')\n",
    "        else:\n",
    "            print('COLDER!')\n",
    "    else:\n",
    "        if abs(num-guess) <= 10:\n",
    "            print('WARM!')\n",
    "        else:\n",
    "            print('COLD!')    \n",
    "   \n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
